homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  packages: !include_dir_named packages

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

default_config:
websocket_api:
discovery:

hacs:
  token: !secret github_access_token

system_health:

vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_blid
    password: !secret roomba_password

plex:
  host: !secret plex_ip
  port: 32400
  token: !secret plex_token
  ssl: false
  verify_ssl: false
  media_player:
    use_episode_art: true
    show_all_controls: true

webostv:
  - host: !secret lg_ip
    name: 'LG TV'
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret lg_mac
    customize:
      sources:
        - netflix
        - youtube
        - plex
        - hdmi1
        - hmdi2
        - hmdi3
        - hmdi4
notify:

media_player:
  - platform: webostv
    host: !secret lg_ip
    name: 'LG TV'

