homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  packages: !include_dir_named packages
  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml

lovelace:
  mode: yaml

default_config:
websocket_api:
config:
discovery:

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key

hacs:
  token: !secret github_access_token

system_health:

vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_blid
    password: !secret roomba_password

ios:


plex:
  host: !secret plex_ip
  port: 32400
  token: !secret plex_token
  ssl: false
  verify_ssl: false
  media_player:
    use_episode_art: true
    show_all_controls: true

webostv:
  - host: !secret lg_ip
    name: 'LG TV'
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret lg_mac
    customize:
      sources:
        - netflix
        - youtube
        - plex
        - hdmi1
        - hmdi2
        - hmdi3
        - hmdi4
notify:

media_player:
  - platform: webostv
    host: !secret lg_ip
    name: 'LG TV'

sensor:
  - platform: sensehat
    display_options:
        - temperature
        - humidity
        - pressure

  - platform: template
    sensors:
      sensehat_temperature:
        value_template: "{{ states('sensor.temperature') | round(1) }}"
        unit_of_measurement: '°C'
      sensehat_pressure:
        value_template: "{{ states('sensor.pressure') | round(1) }}"
        unit_of_measurement: 'hPa'
      sensehat_humidity:
        value_template: "{{ states('sensor.humidity') | round(1) }}"
        unit_of_measurement: '%'

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: load_15m
      - type: network_in
        arg: wlan0
      - type: network_out
        arg: wlan0
      - type: ipv4_address
      - type: processor_use
      - type: last_boot
